Remove fixed jmeter arguments
Removing fixed jmeter arguments enables, for example, the creation of html reports using this format:

`jmeter -g <result-file> -o <html-path>`

This is not currently possible because the `-n` arg conflicts with `-g`:

```
Error: Incompatible options --n/--nongui and -g/--reportonly found.
```